# File: docker-compose.yml
version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - data-volume:/data
    environment:
      - FLASK_ENV=production
      - DOCKER_ENV=1
      - FETCH_DATA_URL=http://host.docker.internal:6951
    depends_on:
      - refresh
    command: >
      sh -c "while [ ! -f /data/recommendation_service.pkl ]; do sleep 1; done && python app.py"

  refresh:
    build: .
    volumes:
      - data-volume:/data
      - ./cron:/etc/cron.d
    environment:
      - DOCKER_ENV=1
      - FETCH_DATA_URL=http://host.docker.internal:6951
    command: >
      sh -c "
        # Install cron + curl in the container
        apt-get update && apt-get install -y cron curl &&

        # Run the initial training once at startup
        python refresh.py &&

        # Overwrite /etc/cron.d/refresh_cron with two lines:
        # 1) Retrain the model
        # 2) Then reload it in the api container
        echo '*/1 * * * * /usr/local/bin/python /app/refresh.py >> /var/log/cron.log 2>&1' > /etc/cron.d/refresh_cron &&
        echo '*/1 * * * * curl -X POST http://api:5000/reload-model >> /var/log/cron.log 2>&1' >> /etc/cron.d/refresh_cron &&

        # Cron housekeeping
        chmod 0644 /etc/cron.d/refresh_cron &&
        crontab /etc/cron.d/refresh_cron &&
        touch /var/log/cron.log &&
        cron && tail -f /var/log/cron.log
      "

volumes:
  data-volume:
