version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - data-volume:/data
    environment:
      - FLASK_ENV=production
    depends_on:
      - refresh
    command: ["python", "app.py"]

  refresh:
    build: .
    volumes:
      - data-volume:/data
      - ./cron:/etc/cron.d
    command: >
      sh -c "apt-get update && apt-get install -y cron &&
             cp /etc/cron.d/refresh_cron /etc/cron.d/refresh_cron &&
             chmod 0644 /etc/cron.d/refresh_cron &&
             crontab /etc/cron.d/refresh_cron &&
             touch /var/log/cron.log &&
             cron && tail -f /var/log/cron.log"

volumes:
  data-volume: